language: python
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"


jobs:
  include:
  - stage: format-check
    python: "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .
  fast_finish: true

# command to install dependencies
install:
  - "pip install -e ."
# command to run tests
script:
  - ./run_tests.sh
deploy:
- provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "3.6"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
